// Call Script Templates - Personalization and script management
export interface ScriptTemplate {
  id: string;
  name: string;
  type: 'web-design' | 'ai-chatbot' | 'general';
  intro: string;
  hook: string;
  qualify: string;
  pitch: string;
  book: string;
  voicemail: string;
}

export interface ProspectData {
  firstName: string;
  lastName?: string;
  company: string;
  phone: string;
  website?: string;
  industry?: string;
  observation?: string;
  city?: string;
  state?: string;
}

export interface PersonalizedScript {
  intro: string;
  hook: string;
  qualify: string;
  pitch: string;
  book: string;
  voicemail: string;
  fullScript: string;
}

// Script templates for different campaign types
export const SCRIPT_TEMPLATES: Record<string, ScriptTemplate> = {
  'web-design': {
    id: 'web-design',
    name: 'Website Modernization',
    type: 'web-design',
    intro: 'Hi {{first_name}}, this is {{agent_name}} calling from RenderWiseAI.',
    hook: "I took a look at {{company}}'s website and noticed {{observation}}. We help businesses like yours modernize their web presence and add AI-powered customer follow-up.",
    qualify: 'Are you currently looking to update your website or improve how you handle incoming leads?',
    pitch: "We've helped local businesses increase their lead conversion by 40% with a modern site plus an AI assistant that follows up with every visitor. Takes about 2 weeks to set up.",
    book: "I'd love to set up a quick 15-minute call with our founder to show you what this looks like for {{company}}. What day works best this week?",
    voicemail: "Hey {{first_name}}, this is {{agent_name}} from RenderWiseAI. I was looking at {{company}}'s website and had a couple ideas that could help you get more customers online. Give me a call back at this number or I'll try you again in a couple days. Have a good one!",
  },
  'ai-chatbot': {
    id: 'ai-chatbot',
    name: 'AI Customer Assistant',
    type: 'ai-chatbot',
    intro: 'Hi {{first_name}}, this is {{agent_name}} calling from RenderWiseAI.',
    hook: "I came across {{company}} while researching {{industry}} businesses in {{city}}. I noticed you might be missing out on leads that visit your site after hours.",
    qualify: 'How do you currently handle website visitors who have questions outside of business hours?',
    pitch: "We build AI assistants that engage every visitor 24/7, answer common questions, and capture lead information. Our clients see a 3x increase in qualified leads within the first month.",
    book: "I'd love to show you a quick demo of what this would look like for {{company}}. Do you have 15 minutes this week for a brief call?",
    voicemail: "Hey {{first_name}}, this is {{agent_name}} from RenderWiseAI. I was checking out {{company}} online and wanted to share how an AI assistant could help you capture more leads after hours. Give me a call back or I'll follow up soon. Thanks!",
  },
  'general': {
    id: 'general',
    name: 'General Outreach',
    type: 'general',
    intro: 'Hi {{first_name}}, this is {{agent_name}} calling from RenderWiseAI.',
    hook: "I've been researching {{industry}} companies in the {{city}} area and {{company}} caught my attention. We specialize in helping businesses like yours grow their online presence.",
    qualify: "What's your biggest challenge right now when it comes to getting new customers online?",
    pitch: "We help businesses modernize their digital presence and automate their lead follow-up. Most of our clients see significant improvements in their conversion rates within the first month.",
    book: "I'd love to set up a quick 15-minute call to learn more about {{company}} and see if we might be a good fit. What does your schedule look like this week?",
    voicemail: "Hey {{first_name}}, this is {{agent_name}} from RenderWiseAI. I was researching {{industry}} businesses and wanted to reach out about {{company}}. Give me a call back at this number when you have a moment. Thanks!",
  },
};

// Default agent configuration
export const DEFAULT_AGENT_CONFIG = {
  name: 'Alex',
  company: 'RenderWiseAI',
  phone: '+17704077842',
};

/**
 * Generate a personalized observation about a prospect's website
 * This would normally be generated by an AI analyzing their site
 */
export function generateObservation(prospect: ProspectData): string {
  const observations = [
    `the site could benefit from a more modern, mobile-friendly design`,
    `you're not currently capturing visitor information for follow-up`,
    `the site loads a bit slowly on mobile devices`,
    `there's an opportunity to add an AI chat feature for 24/7 customer engagement`,
    `the contact form could be more prominent to capture more leads`,
    `the site isn't optimized for local search in ${prospect.city || 'your area'}`,
    `you're missing out on after-hours leads that an AI assistant could capture`,
  ];

  // In a real implementation, this would use AI to analyze the actual website
  // For now, return a random observation
  return observations[Math.floor(Math.random() * observations.length)];
}

/**
 * Personalize a script template with prospect data
 */
export function personalizeScript(
  templateId: string,
  prospect: ProspectData,
  agentConfig: typeof DEFAULT_AGENT_CONFIG = DEFAULT_AGENT_CONFIG
): PersonalizedScript {
  console.log('[call-script.personalizeScript] Personalizing script for:', prospect.firstName, prospect.company);
  
  const template = SCRIPT_TEMPLATES[templateId] || SCRIPT_TEMPLATES['general'];
  const observation = prospect.observation || generateObservation(prospect);

  const variables: Record<string, string> = {
    first_name: prospect.firstName,
    last_name: prospect.lastName || '',
    company: prospect.company,
    industry: prospect.industry || 'local business',
    city: prospect.city || 'your area',
    state: prospect.state || '',
    observation,
    agent_name: agentConfig.name,
    agent_company: agentConfig.company,
    agent_phone: agentConfig.phone,
  };

  const personalize = (text: string): string => {
    return text.replace(/\{\{(\w+)\}\}/g, (match, key) => variables[key] || match);
  };

  const personalized: PersonalizedScript = {
    intro: personalize(template.intro),
    hook: personalize(template.hook),
    qualify: personalize(template.qualify),
    pitch: personalize(template.pitch),
    book: personalize(template.book),
    voicemail: personalize(template.voicemail),
    fullScript: '',
  };

  // Build full script for reference
  personalized.fullScript = `${personalized.intro}

${personalized.hook}

${personalized.qualify}

${personalized.pitch}

${personalized.book}`;

  console.log('[call-script.personalizeScript] Script personalized successfully');
  console.log('[call-script.personalizeScript] Intro:', personalized.intro);
  
  return personalized;
}

/**
 * Get a script template by ID
 */
export function getScriptTemplate(templateId: string): ScriptTemplate {
  return SCRIPT_TEMPLATES[templateId] || SCRIPT_TEMPLATES['general'];
}

/**
 * List all available script templates
 */
export function listScriptTemplates(): ScriptTemplate[] {
  return Object.values(SCRIPT_TEMPLATES);
}

/**
 * Generate a voicemail script for a prospect
 */
export function generateVoicemailScript(
  prospect: ProspectData,
  templateId: string = 'web-design',
  agentConfig: typeof DEFAULT_AGENT_CONFIG = DEFAULT_AGENT_CONFIG
): string {
  const personalized = personalizeScript(templateId, prospect, agentConfig);
  return personalized.voicemail;
}

/**
 * Generate the initial conversation prompt for the AI voice agent
 */
export function generateConversationPrompt(
  prospect: ProspectData,
  templateId: string = 'web-design'
): { systemPrompt: string; firstMessage: string } {
  const personalized = personalizeScript(templateId, prospect);

  const systemPrompt = `You are ${DEFAULT_AGENT_CONFIG.name}, a friendly sales representative from ${DEFAULT_AGENT_CONFIG.company}.

You are calling ${prospect.firstName} from ${prospect.company}.

CONVERSATION SCRIPT:
${personalized.fullScript}

OBJECTION HANDLING:
- "Not interested" → "Totally understand. Just out of curiosity, are you happy with how your website converts visitors right now? ... No pressure at all, I'll let you go. Have a great day!"
- "How much does it cost?" → "It depends on what you need — a basic website revamp starts around \$500, and the AI assistant is a monthly service. That's exactly what the 15-min call covers — no commitment, just a quick look at what would work for you."
- "Send me an email" → "Absolutely! What's the best email? I'll have our team send over some examples of what we've done for similar businesses." (capture email)
- "I already have a website" → "That's great! When was the last time it was updated? A lot of businesses we work with had sites but they weren't mobile-optimized or converting visitors into leads."
- "Call back later" → "No problem! When's a better time? I'll make sure to call back then." (schedule callback)

RULES:
- Be friendly, professional, and concise
- Listen actively and respond naturally
- Don't be pushy — one objection response then move on
- Always try to book the 15-minute call
- If they want to end the call, be polite and professional`;

  return {
    systemPrompt,
    firstMessage: `${personalized.intro} ${personalized.hook}`,
  };
}
